-- Relay handoff (Option 3, PLAN-HumanHandoff.md): a per-escalation session that
-- mirrors the customer's thread to staff phones and routes staff replies back.
-- One ACTIVE relay per thread at a time; `tag` is the short human-friendly id
-- staff use to address a session (#12) when not quote-replying.
create table if not exists handoff_relays (
  id uuid primary key default gen_random_uuid(),
  tag bigint generated by default as identity,
  thread_id uuid not null references threads(id) on delete cascade,
  status text not null default 'active' check (status in ('active','closed')),
  customer_phone text,
  customer_name text,
  customer_channel text not null default 'whatsapp' check (customer_channel in ('whatsapp','sms')),
  reason text,
  opened_by text not null default 'escalation',
  -- Set once the staff alert actually went out. If the serverless invocation dies
  -- between inserting this row and broadcasting, the next escalation for the same
  -- thread sees alerted_at IS NULL and sends the alert itself instead of assuming
  -- staff already know.
  alerted_at timestamptz,
  staff_reply_count int not null default 0,
  -- Set once, when the customer has been told staff are slow to arrive; prevents
  -- repeating the "you can also call us" nudge on every subsequent message.
  customer_nudged_at timestamptz,
  last_activity_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create unique index if not exists handoff_relays_one_active_per_thread
  on handoff_relays (thread_id) where (status = 'active');
create index if not exists handoff_relays_status_idx on handoff_relays (status, last_activity_at);

-- Message-SID ledger, three uses (`kind`):
--   mirror           — outbound SID of a message we mirrored TO a staff phone; a
--                      WhatsApp quote-reply (Twilio's OriginalRepliedMessageSid)
--                      resolves through it to the right relay.
--   customer_inbound — inbound SID of a customer message that WAS mirrored;
--                      makes mirroring idempotent when Twilio redelivers a
--                      webhook that timed out mid-mirror.
--   staff_inbound    — inbound SID of a staff message that WAS relayed to the
--                      customer; stops a webhook retry double-sending it.
create table if not exists handoff_relay_mirrors (
  id uuid primary key default gen_random_uuid(),
  relay_id uuid not null references handoff_relays(id) on delete cascade,
  kind text not null default 'mirror' check (kind in ('mirror','customer_inbound','staff_inbound')),
  message_sid text not null,
  staff_phone text,
  created_at timestamptz not null default now()
);

create index if not exists handoff_relay_mirrors_sid_idx on handoff_relay_mirrors (message_sid);
create index if not exists handoff_relay_mirrors_staff_idx on handoff_relay_mirrors (staff_phone, created_at desc) where kind = 'mirror';
-- Idempotency kinds must be claimable exactly once: concurrent webhook retries
-- race on this unique index, and the loser must NOT send. ('mirror' rows are
-- excluded — their SIDs are provider-generated and inherently unique.)
create unique index if not exists handoff_relay_mirrors_dedupe_idx
  on handoff_relay_mirrors (kind, message_sid) where kind in ('customer_inbound','staff_inbound');
